
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4
      # Set Node.js version
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Set DATABASE_URL
      run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
    - run: pnpm install
    - run: pnpx prisma migrate dev
    - run: pnpx prisma generate
    - run: pnpm run build
    - run: pnpm run test


    









